services:
  - type: web
    name: bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    
  - type: web
    name: shopbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python shopbot.py

